package entity;

// Generated Mar 11, 2016 5:28:01 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Batchmaster generated by hbm2java
 */
@Entity
@Table(name = "batchmaster", schema = "public")
public class Batchmaster implements java.io.Serializable {

	private long recordid;
	private String batch;
	private String batchDescription;
	private BigDecimal fees;
	private String batchcode;
	private BigDecimal numofstud;

	public Batchmaster() {
	}

	public Batchmaster(long recordid) {
		this.recordid = recordid;
	}

	public Batchmaster(long recordid, String batch, String batchDescription,
			BigDecimal fees, String batchcode, BigDecimal numofstud) {
		this.recordid = recordid;
		this.batch = batch;
		this.batchDescription = batchDescription;
		this.fees = fees;
		this.batchcode = batchcode;
		this.numofstud = numofstud;
	}

	@Id
	@Column(name = "recordid", unique = true, nullable = false)
	public long getRecordid() {
		return this.recordid;
	}

	public void setRecordid(long recordid) {
		this.recordid = recordid;
	}

	@Column(name = "batch", length = 50)
	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	@Column(name = "batch_description", length = 50)
	public String getBatchDescription() {
		return this.batchDescription;
	}

	public void setBatchDescription(String batchDescription) {
		this.batchDescription = batchDescription;
	}

	@Column(name = "fees", precision = 65535, scale = 65531)
	public BigDecimal getFees() {
		return this.fees;
	}

	public void setFees(BigDecimal fees) {
		this.fees = fees;
	}

	@Column(name = "batchcode", length = 5)
	public String getBatchcode() {
		return this.batchcode;
	}

	public void setBatchcode(String batchcode) {
		this.batchcode = batchcode;
	}

	@Column(name = "numofstud", precision = 65535, scale = 65531)
	public BigDecimal getNumofstud() {
		return this.numofstud;
	}

	public void setNumofstud(BigDecimal numofstud) {
		this.numofstud = numofstud;
	}

}
