package entity;
// Generated 3-Apr-2017 1:25:04 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Donor generated by hbm2java
 */
@Entity
@Table(name = "donor", schema = "public")
public class Donor implements java.io.Serializable {

	private long recordid;
	private String firstname;
	private String lastname;
	private String phone1;
	private String phone2;
	private String email;
	private String age;
	private String dob;
	private String weight;
	private String city;
	private String province;
	private String country;
	private String bloodgrp;

	public Donor() {
	}

	public Donor(long recordid) {
		this.recordid = recordid;
	}

	public Donor(long recordid, String firstname, String lastname, String phone1, String phone2, String email,
			String age, String dob, String weight, String city, String province, String country, String bloodgrp) {
		this.recordid = recordid;
		this.firstname = firstname;
		this.lastname = lastname;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.email = email;
		this.age = age;
		this.dob = dob;
		this.weight = weight;
		this.city = city;
		this.province = province;
		this.country = country;
		this.bloodgrp = bloodgrp;
	}

	@Id

	@Column(name = "recordid", unique = true, nullable = false, precision = 10, scale = 0)
	public long getRecordid() {
		return this.recordid;
	}

	public void setRecordid(long recordid) {
		this.recordid = recordid;
	}

	@Column(name = "firstname", length = 20)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 20)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "phone1", length = 10)
	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	@Column(name = "phone2", length = 10)
	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	@Column(name = "email", length = 25)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "age", length = 3)
	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	@Column(name = "dob", length = 8)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "weight", length = 10)
	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	@Column(name = "city", length = 25)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "province", length = 15)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "country", length = 10)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "bloodgrp", length = 2)
	public String getBloodgrp() {
		return this.bloodgrp;
	}

	public void setBloodgrp(String bloodgrp) {
		this.bloodgrp = bloodgrp;
	}

}
