package entity;

// Generated Mar 11, 2016 6:07:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Feesmaster generated by hbm2java
 */
@Entity
@Table(name = "feesmaster", schema = "public")
public class Feesmaster implements java.io.Serializable {

	private String transId;
	private String studentid;
	private String studentname;
	private Integer totalFees;
	private Integer amount;
	private Integer outstanding;
	private Date paymentDate;
	private String userid;
	private String modeofpayment;
	private String modeDescription;
	private String transType;

	public Feesmaster() {
	}

	public Feesmaster(String transId) {
		this.transId = transId;
	}

	public Feesmaster(String transId, String studentid, String studentname,
			Integer totalFees, Integer amount, Integer outstanding,
			Date paymentDate, String userid, String modeofpayment,
			String modeDescription, String transType) {
		this.transId = transId;
		this.studentid = studentid;
		this.studentname = studentname;
		this.totalFees = totalFees;
		this.amount = amount;
		this.outstanding = outstanding;
		this.paymentDate = paymentDate;
		this.userid = userid;
		this.modeofpayment = modeofpayment;
		this.modeDescription = modeDescription;
		this.transType = transType;
	}

	@Id
	@Column(name = "trans_id", unique = true, nullable = false, length = 25)
	public String getTransId() {
		return this.transId;
	}

	public void setTransId(String transId) {
		this.transId = transId;
	}

	@Column(name = "studentid", length = 10)
	public String getStudentid() {
		return this.studentid;
	}

	public void setStudentid(String studentid) {
		this.studentid = studentid;
	}

	@Column(name = "studentname", length = 30)
	public String getStudentname() {
		return this.studentname;
	}

	public void setStudentname(String studentname) {
		this.studentname = studentname;
	}

	@Column(name = "total_fees", precision = 5, scale = 0)
	public Integer getTotalFees() {
		return this.totalFees;
	}

	public void setTotalFees(Integer totalFees) {
		this.totalFees = totalFees;
	}

	@Column(name = "amount", precision = 5, scale = 0)
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	@Column(name = "outstanding", precision = 5, scale = 0)
	public Integer getOutstanding() {
		return this.outstanding;
	}

	public void setOutstanding(Integer outstanding) {
		this.outstanding = outstanding;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "payment_date", length = 4)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "userid", length = 10)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "modeofpayment", length = 10)
	public String getModeofpayment() {
		return this.modeofpayment;
	}

	public void setModeofpayment(String modeofpayment) {
		this.modeofpayment = modeofpayment;
	}

	@Column(name = "mode_description", length = 50)
	public String getModeDescription() {
		return this.modeDescription;
	}

	public void setModeDescription(String modeDescription) {
		this.modeDescription = modeDescription;
	}

	@Column(name = "trans_type", length = 2)
	public String getTransType() {
		return this.transType;
	}

	public void setTransType(String transType) {
		this.transType = transType;
	}

}
