package entity;

// Generated Mar 11, 2016 5:28:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Paramaster generated by hbm2java
 */
@Entity
@Table(name = "paramaster", schema = "public")
public class Paramaster implements java.io.Serializable {

	private long recordid;
	private String type;
	private String code;
	private String sdesc;
	private String ldesc;

	public Paramaster() {
	}

	public Paramaster(long recordid) {
		this.recordid = recordid;
	}

	public Paramaster(long recordid, String type, String code, String sdesc,
			String ldesc) {
		this.recordid = recordid;
		this.type = type;
		this.code = code;
		this.sdesc = sdesc;
		this.ldesc = ldesc;
	}

	@Id
	@Column(name = "recordid", unique = true, nullable = false)
	public long getRecordid() {
		return this.recordid;
	}

	public void setRecordid(long recordid) {
		this.recordid = recordid;
	}

	@Column(name = "type", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "code", length = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "sdesc", length = 60)
	public String getSdesc() {
		return this.sdesc;
	}

	public void setSdesc(String sdesc) {
		this.sdesc = sdesc;
	}

	@Column(name = "ldesc", length = 60)
	public String getLdesc() {
		return this.ldesc;
	}

	public void setLdesc(String ldesc) {
		this.ldesc = ldesc;
	}

}
