package entity;

// Generated Mar 11, 2016 5:28:01 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Staffmaster generated by hbm2java
 */
@Entity
@Table(name = "staffmaster", schema = "public")
public class Staffmaster implements java.io.Serializable {

	private long recordid;
	private String name;
	private String id;
	private String role;
	private String grade;
	private Integer salary;
	private String status;
	private String prefix;

	public Staffmaster() {
	}

	public Staffmaster(long recordid) {
		this.recordid = recordid;
	}

	public Staffmaster(long recordid, String name, String id, String role,
			String grade, Integer salary, String status, String prefix) {
		this.recordid = recordid;
		this.name = name;
		this.id = id;
		this.role = role;
		this.grade = grade;
		this.salary = salary;
		this.status = status;
		this.prefix = prefix;
	}

	@Id
	@Column(name = "recordid", unique = true, nullable = false)
	public long getRecordid() {
		return this.recordid;
	}

	public void setRecordid(long recordid) {
		this.recordid = recordid;
	}

	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "id", length = 5)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "role", length = 15)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "grade", length = 10)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "salary", precision = 5, scale = 0)
	public Integer getSalary() {
		return this.salary;
	}

	public void setSalary(Integer salary) {
		this.salary = salary;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "prefix", length = 5)
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

}
