package entity;

// Generated Mar 11, 2016 5:28:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Studentmaster generated by hbm2java
 */
@Entity
@Table(name = "studentmaster", schema = "public")
@SequenceGenerator(name="studentmaster_studentid_seq",sequenceName="studentmaster_studentid_seq")
public class Studentmaster implements java.io.Serializable {

	private long studentid;
	private String firstname;
	private String middlename;
	private String lastname;
	private String address;
	private String contactnumber1;
	private String contactnumber2;
	private String bloodgrp;
	private Date dob;
	private String schoolname;
	private String standard;
	private String fathername;
	private String mothername;
	private String parentcontactnumber1;
	private String parentcontactnumber2;
	private String batch;
	private Date doj;
	private Integer totalfees;
	private String gender;
	private String emailid;
	private String formnumber;
	private String english;
	private String gujarati;
	private String maths;
	private String science;
	private String socialscience;
	private String sanskrit;
	private String hindi;
	private String computer;
	private String board;
	private String medium;
	private String maker;
	private Date recDate;
	private String recTime;
	private String prefix;
	private String fullname;
	private String recstatus;

	public Studentmaster() {
	}

	public Studentmaster(long studentid) {
		this.studentid = studentid;
	}

	public Studentmaster(long studentid, String firstname, String middlename,
			String lastname, String address, String contactnumber1,
			String contactnumber2, String bloodgrp, Date dob,
			String schoolname, String standard, String fathername,
			String mothername, String parentcontactnumber1,
			String parentcontactnumber2, String batch, Date doj,
			Integer totalfees, String gender, String emailid,
			String formnumber, String english, String gujarati, String maths,
			String science, String socialscience, String sanskrit,
			String hindi, String computer, String board, String medium,
			String maker, Date recDate, String recTime, String prefix,
			String fullname, String recstatus) {
		this.studentid = studentid;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.address = address;
		this.contactnumber1 = contactnumber1;
		this.contactnumber2 = contactnumber2;
		this.bloodgrp = bloodgrp;
		this.dob = dob;
		this.schoolname = schoolname;
		this.standard = standard;
		this.fathername = fathername;
		this.mothername = mothername;
		this.parentcontactnumber1 = parentcontactnumber1;
		this.parentcontactnumber2 = parentcontactnumber2;
		this.batch = batch;
		this.doj = doj;
		this.totalfees = totalfees;
		this.gender = gender;
		this.emailid = emailid;
		this.formnumber = formnumber;
		this.english = english;
		this.gujarati = gujarati;
		this.maths = maths;
		this.science = science;
		this.socialscience = socialscience;
		this.sanskrit = sanskrit;
		this.hindi = hindi;
		this.computer = computer;
		this.board = board;
		this.medium = medium;
		this.maker = maker;
		this.recDate = recDate;
		this.recTime = recTime;
		this.prefix = prefix;
		this.fullname = fullname;
		this.recstatus = recstatus;
	}

	@Id
	@GeneratedValue(generator="studentmaster_studentid_seq",strategy=GenerationType.AUTO)
	@Column(name = "studentid", unique = true, nullable = false)
	public long getStudentid() {
		return this.studentid;
	}

	public void setStudentid(long studentid) {
		this.studentid = studentid;
	}

	@Column(name = "firstname", length = 20)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "middlename", length = 20)
	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	@Column(name = "lastname", length = 20)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "address", length = 150)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "contactnumber1", length = 13)
	public String getContactnumber1() {
		return this.contactnumber1;
	}

	public void setContactnumber1(String contactnumber1) {
		this.contactnumber1 = contactnumber1;
	}

	@Column(name = "contactnumber2", length = 13)
	public String getContactnumber2() {
		return this.contactnumber2;
	}

	public void setContactnumber2(String contactnumber2) {
		this.contactnumber2 = contactnumber2;
	}

	@Column(name = "bloodgrp", length = 3)
	public String getBloodgrp() {
		return this.bloodgrp;
	}

	public void setBloodgrp(String bloodgrp) {
		this.bloodgrp = bloodgrp;
	}
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 4)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "schoolname", length = 70)
	public String getSchoolname() {
		return this.schoolname;
	}

	public void setSchoolname(String schoolname) {
		this.schoolname = schoolname;
	}

	@Column(name = "standard", length = 2)
	public String getStandard() {
		return this.standard;
	}

	public void setStandard(String standard) {
		this.standard = standard;
	}

	@Column(name = "fathername", length = 30)
	public String getFathername() {
		return this.fathername;
	}

	public void setFathername(String fathername) {
		this.fathername = fathername;
	}

	@Column(name = "mothername", length = 30)
	public String getMothername() {
		return this.mothername;
	}

	public void setMothername(String mothername) {
		this.mothername = mothername;
	}

	@Column(name = "parentcontactnumber1", length = 13)
	public String getParentcontactnumber1() {
		return this.parentcontactnumber1;
	}

	public void setParentcontactnumber1(String parentcontactnumber1) {
		this.parentcontactnumber1 = parentcontactnumber1;
	}

	@Column(name = "parentcontactnumber2", length = 13)
	public String getParentcontactnumber2() {
		return this.parentcontactnumber2;
	}

	public void setParentcontactnumber2(String parentcontactnumber2) {
		this.parentcontactnumber2 = parentcontactnumber2;
	}

	@Column(name = "batch", length = 25)
	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "doj", length = 4)
	public Date getDoj() {
		return this.doj;
	}

	public void setDoj(Date doj) {
		this.doj = doj;
	}

	@Column(name = "totalfees", precision = 6, scale = 0)
	public Integer getTotalfees() {
		return this.totalfees;
	}

	public void setTotalfees(Integer totalfees) {
		this.totalfees = totalfees;
	}

	@Column(name = "gender", length = 6)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "emailid", length = 30)
	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	@Column(name = "formnumber", length = 10)
	public String getFormnumber() {
		return this.formnumber;
	}

	public void setFormnumber(String formnumber) {
		this.formnumber = formnumber;
	}

	@Column(name = "english", length = 1)
	public String getEnglish() {
		return this.english;
	}

	public void setEnglish(String english) {
		this.english = english;
	}

	@Column(name = "gujarati", length = 1)
	public String getGujarati() {
		return this.gujarati;
	}

	public void setGujarati(String gujarati) {
		this.gujarati = gujarati;
	}

	@Column(name = "maths", length = 1)
	public String getMaths() {
		return this.maths;
	}

	public void setMaths(String maths) {
		this.maths = maths;
	}

	@Column(name = "science", length = 1)
	public String getScience() {
		return this.science;
	}

	public void setScience(String science) {
		this.science = science;
	}

	@Column(name = "socialscience", length = 1)
	public String getSocialscience() {
		return this.socialscience;
	}

	public void setSocialscience(String socialscience) {
		this.socialscience = socialscience;
	}

	@Column(name = "sanskrit", length = 1)
	public String getSanskrit() {
		return this.sanskrit;
	}

	public void setSanskrit(String sanskrit) {
		this.sanskrit = sanskrit;
	}

	@Column(name = "hindi", length = 1)
	public String getHindi() {
		return this.hindi;
	}

	public void setHindi(String hindi) {
		this.hindi = hindi;
	}

	@Column(name = "computer", length = 1)
	public String getComputer() {
		return this.computer;
	}

	public void setComputer(String computer) {
		this.computer = computer;
	}

	@Column(name = "board", length = 10)
	public String getBoard() {
		return this.board;
	}

	public void setBoard(String board) {
		this.board = board;
	}

	@Column(name = "medium", length = 25)
	public String getMedium() {
		return this.medium;
	}

	public void setMedium(String medium) {
		this.medium = medium;
	}

	@Column(name = "maker", length = 20)
	public String getMaker() {
		return this.maker;
	}

	public void setMaker(String maker) {
		this.maker = maker;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rec_date", length = 4)
	public Date getRecDate() {
		return this.recDate;
	}

	public void setRecDate(Date recDate) {
		this.recDate = recDate;
	}

	@Column(name = "rec_time", length = 10)
	public String getRecTime() {
		return this.recTime;
	}

	public void setRecTime(String recTime) {
		this.recTime = recTime;
	}

	@Column(name = "prefix", length = 5)
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Column(name = "fullname", length = 40)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "recstatus", length = 1)
	public String getRecstatus() {
		return this.recstatus;
	}

	public void setRecstatus(String recstatus) {
		this.recstatus = recstatus;
	}

}
