package entity;
// Generated 3-Apr-2017 1:25:04 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usermaster generated by hbm2java
 */
@Entity
@Table(name = "usermaster", schema = "public")
public class Usermaster implements java.io.Serializable {

	private String username;
	private String userlevel;
	private String role;
	private String password;
	private Date logindate;
	private String logintime;
	private String firstname;
	private String lastname;
	private long recordid;

	public Usermaster() {
	}

	public Usermaster(String username, long recordid) {
		this.username = username;
		this.recordid = recordid;
	}

	public Usermaster(String username, String userlevel, String role, String password, Date logindate, String logintime,
			String firstname, String lastname, long recordid) {
		this.username = username;
		this.userlevel = userlevel;
		this.role = role;
		this.password = password;
		this.logindate = logindate;
		this.logintime = logintime;
		this.firstname = firstname;
		this.lastname = lastname;
		this.recordid = recordid;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 10)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "userlevel", length = 10)
	public String getUserlevel() {
		return this.userlevel;
	}

	public void setUserlevel(String userlevel) {
		this.userlevel = userlevel;
	}

	@Column(name = "role", length = 10)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "password", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "logindate", length = 4)
	public Date getLogindate() {
		return this.logindate;
	}

	public void setLogindate(Date logindate) {
		this.logindate = logindate;
	}

	@Column(name = "logintime", length = 20)
	public String getLogintime() {
		return this.logintime;
	}

	public void setLogintime(String logintime) {
		this.logintime = logintime;
	}

	@Column(name = "firstname", length = 30)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 30)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "recordid", nullable = false, precision = 10, scale = 0)
	public long getRecordid() {
		return this.recordid;
	}

	public void setRecordid(long recordid) {
		this.recordid = recordid;
	}

}
